[project]
name = "data3001-modelling-f1-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.7",
    "pandas>=2.3.3",
    "scipy>=1.16.3",
    "shapely>=2.1.2",
]
